# Generated by Django 3.1.1 on 2020-10-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_is_activated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
