# Generated by Django 3.1.1 on 2020-10-26 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название задания')),
                ('task_text', models.TextField(db_index=True, max_length=1000, verbose_name='Описание самого задания')),
                ('tests', models.TextField(db_index=True, max_length=1000, verbose_name='Тесты')),
                ('required_form', models.TextField(db_index=True, max_length=1000, verbose_name='Шаблон класса')),
                ('date_publish', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания задания')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher', verbose_name='Учитель, который приудмал это задание')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
