# Generated by Django 3.1.1 on 2020-11-28 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import testing_system.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название курса')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание курса')),
                ('availability', models.CharField(choices=[('true', 'Открытый'), ('false', 'Закрытый')], default='true', max_length=15)),
                ('date_publish', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-date_publish'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название задания', max_length=100, unique=True, verbose_name='Название задания')),
                ('task_text', models.TextField(db_index=True, help_text='Текст задания', max_length=1000, verbose_name='Описание самого задания')),
                ('name_class', models.CharField(default='ReqForm', help_text='Название класса программы', max_length=100, verbose_name='Название класса программы')),
                ('date_publish', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания задания')),
                ('required_form', models.TextField(db_index=True, help_text='Шаблон формы учителя', max_length=1000, verbose_name='Необходимый шаблон класса')),
                ('time_limit', models.PositiveIntegerField(verbose_name='Максимальное время выполнения программы(в милисекундах)')),
                ('memory_limit', models.PositiveIntegerField(verbose_name='Максимальное количество памяти для программы(в байтах)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_system.course', verbose_name='Курс задания')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher', verbose_name='Учитель, который приудмал это задание')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-date_publish'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(db_index=True, help_text='Входные данные', max_length=200, verbose_name='Данные на вход')),
                ('output', models.CharField(db_index=True, help_text='Полученные данные', max_length=200, verbose_name='Данные на выход')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_system.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='StudentCodeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to=testing_system.models.user_directory_path, verbose_name='Загрузка решения')),
                ('code_text', models.TextField(blank=True, db_index=True, max_length=1000, verbose_name='Решение ученика ввиде кода')),
                ('dispatch_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата отправки ответа')),
                ('status', models.CharField(default='Проверяется', help_text='Статус ответа', max_length=1000, verbose_name='Статус ответа')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testing_system.task', verbose_name='Задание на которое был отправлен ответ')),
            ],
            options={
                'verbose_name': 'Модель ответа ученика',
                'verbose_name_plural': 'Модели ответов учеников',
                'ordering': ['-dispatch_time'],
            },
        ),
        migrations.CreateModel(
            name='CourseStudentAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_system.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='testing_system.CourseStudentAccess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_boss', to='main.teacher', verbose_name='Создатель'),
        ),
    ]
