# Generated by Django 3.1.1 on 2020-11-04 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing_system', '0002_auto_20201101_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date_publish'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterField(
            model_name='task',
            name='required_form',
            field=models.TextField(db_index=True, help_text='Шаблон формы учителя', max_length=1000, verbose_name='Шаблон класса, который задал учител'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_text',
            field=models.TextField(db_index=True, help_text='Текст задания', max_length=1000, verbose_name='Описание самого задания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tests',
            field=models.TextField(db_index=True, help_text='Тесты', max_length=1000, verbose_name='Тесты'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Название задания', max_length=100, verbose_name='Название задания'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(db_index=True, help_text='Входные данные', max_length=200, verbose_name='Данные на вход')),
                ('output', models.CharField(db_index=True, help_text='Полученные данные', max_length=200, verbose_name='Данные на выход')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_system.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
    ]
