# Generated by Django 3.1.1 on 2020-11-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_system', '0004_auto_20201106_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tests',
        ),
    ]
