# Generated by Django 3.1.1 on 2020-11-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_system', '0005_remove_task_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcodemodel',
            name='status',
            field=models.CharField(choices=[('err', 'Ошибка'), ('check', 'Проверяется'), ('Ok', 'Ok')], default='s', max_length=16),
        ),
    ]
