# Generated by Django 3.1.1 on 2020-11-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_system', '0006_studentcodemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcodemodel',
            name='status',
            field=models.CharField(help_text='Статус ответа', max_length=100, verbose_name='Статус ответа'),
        ),
    ]
